{% set name = "antmocdata" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/antmocdata-{{ version }}.tar.gz
  sha256: d4a027537c2a3ee2f50112459240d742dee55cb4ab1ef9f794602414ce95167f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - baseopt >=0.1.3
    - h5py
    - numpy
    - pyevtk

test:
  imports:
    - antmocdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ANT-MOC/antmoc-data
  summary: A package for ANT-MOC data manipulation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alephpiece
